user www-data;
worker_processes 1;
pid /run/qianqi-preview.pid;
error_log /var/log/nginx/qianqi-preview-error.log;
events { worker_connections 512; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /var/log/nginx/qianqi-preview-access.log;
    include /opt/rh-preview/nginx-host-server.conf;
}
