const $=id=>document.getElementById(id),key=location.hash.slice(1),providers=new Map();let wallet,view,prepared,busy=false;
history.replaceState(null,'',location.pathname);
async function api(route,value={}){const r=await fetch(route,{method:'POST',headers:{'content-type':'application/json','x-qianqi-session':key},body:JSON.stringify(value)});const result=await r.json();if(!r.ok)throw Error(result.error);return result;}
function announce(e){const {info,provider}=e.detail||{};if(!info||!provider?.request||providers.has(info.uuid))return;providers.set(info.uuid,provider);const o=document.createElement('option');o.value=info.uuid;o.textContent=info.name;$('wallet').append(o);}
window.addEventListener('eip6963:announceProvider',announce);window.dispatchEvent(new Event('eip6963:requestProvider'));
async function identity(){if(!wallet)throw Error('Подключи кошелёк');const [accounts,chain]=await Promise.all([wallet.request({method:'eth_accounts'}),wallet.request({method:'eth_chainId'})]);if(accounts[0]?.toLowerCase()!==view.governor.toLowerCase()||BigInt(chain)!==4663n)throw Error('Нужен управляющий аккаунт и Robinhood Chain');}
async function action(fn){if(busy)return;busy=true;$('sign').disabled=true;try{await fn();}catch(e){$('status').textContent=e.code===4001?'Отменено в кошельке. Если запрос уже подготовлен к отправке, журнал требует сверки; повторно не отправляем.':e.message||'Не удалось завершить действие';}finally{busy=false;}}
function invalidate(){prepared=null;$('sign').disabled=true;$('status').textContent='Кошелёк или сеть изменились. Проверь шаг заново.';}
$('wallet').onchange=()=>{wallet=null;invalidate();};
$('connect').onclick=()=>action(async()=>{wallet=providers.get($('wallet').value);if(!wallet)throw Error('Выбери расширение кошелька');await wallet.request({method:'eth_requestAccounts'});await identity();wallet.on?.('accountsChanged',invalidate);wallet.on?.('chainChanged',invalidate);$('status').textContent='Управляющий кошелёк подключён.';});
$('review').onclick=()=>action(async()=>{prepared=await api('/prepare');$('details').textContent=JSON.stringify({...prepared,request:{...prepared.request,data:prepared.request.data.slice(0,66)+'… (полный bytecode сохранён в локальном плане)'}},null,2);$('status').textContent=view.allowSend?'Шаг проверен. Подпись доступна в течение минуты.':'Режим проверки: подписи и отправки выключены.';$('sign').disabled=!view.allowSend;});
$('sign').onclick=()=>action(async()=>{await identity();if(!prepared||prepared.expiresAt<Date.now())throw Error('Проверка устарела');const request=await api('/intent',{id:prepared.id});await identity();const txHash=await wallet.request({method:'eth_sendTransaction',params:[request]});$('txhash').value=txHash;localStorage.setItem('qianqi-deployment-last-hash',txHash);await api('/submitted',{hash:txHash});$('status').textContent='Хеш сохранён. Проверь подтверждение перед следующим шагом.';prepared=null;});
$('refresh').onclick=()=>action(async()=>{$('details').textContent=JSON.stringify(await api('/refresh'),null,2);});
$('recover').onclick=()=>action(async()=>{$('details').textContent=JSON.stringify(await api('/submitted',{hash:$('txhash').value.trim()}),null,2);});
api('/view').then(v=>{view=v;$('details').textContent=JSON.stringify(v,null,2);$('status').textContent=v.allowSend?'Подписи включены: каждый шаг требует твоего клика.':'Режим проверки. Отправки выключены.';$('txhash').value=localStorage.getItem('qianqi-deployment-last-hash')||'';}).catch(()=>{$('status').textContent='Открой исходную ссылку из CLI с ключом сессии.';});
