const {test}=require('node:test'),assert=require('node:assert/strict');
const {chromium}=require('@playwright/test');const {createSite}=require('../scripts/serve-site.cjs');
test('token balance reads exact units, ignores an obsolete account response and clears on disconnect',async t=>{
 const server=createSite();await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch();t.after(async()=>{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));});const page=await browser.newPage();
 await page.route('https://www.geckoterminal.com/**',r=>r.fulfill({body:'Chart fixture'}));
 await page.addInitScript(()=>{window.events={};window.mode='normal';window.ethereum={on:(n,f)=>events[n]=f,removeListener:()=>{},request:async({method,params})=>{if(method==='eth_requestAccounts')return ['0x'+'1'.repeat(40)];if(method==='eth_chainId')return '0x1237';if(method==='eth_call'){if(params[0].data==='0x313ce567')return '0x'+(18).toString(16).padStart(64,'0');if(window.mode==='delay')return new Promise(r=>window.finishBalance=r);if(window.mode==='error')throw Error();return '0x'+(123456789012345678901234n).toString(16).padStart(64,'0');}throw Error(method);}};});
 await page.goto(`http://127.0.0.1:${server.address().port}/concepts/hk/`);await page.locator('header .connect').click();await page.waitForFunction(()=>document.getElementById('token-balance').textContent==='123,456.789012345678901234');
 await page.evaluate(()=>{window.mode='delay';events.accountsChanged(['0x'+'2'.repeat(40)]);});await page.waitForFunction(()=>typeof window.finishBalance==='function');await page.evaluate(()=>{window.mode='error';events.accountsChanged(['0x'+'3'.repeat(40)]);});await page.waitForFunction(()=>document.getElementById('token-balance').textContent==='Unable to load');await page.evaluate(()=>finishBalance('0x'+'0'.repeat(64)));assert.equal(await page.locator('#token-balance').textContent(),'Unable to load');await page.locator('#disconnect').click();assert.equal(await page.locator('#token-balance').textContent(),'—');
});
